# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d220ac72f1b1f7731ed4a97f54cde38c7a80f41b5a18fd95e549afdefa1799ec36aef6860ec4dfb197cbade6ced3abafa25cea73831d337c69904292d9242247

test:
  secret_key_base: 034dcdba8c3e484b619b6744f6eb664afc8c680c22dba13c848805e448d2262d18eeabd40ffdc7927aa4f1a70d50782f900a2d44755f5e0a2889e537fd8868e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
